spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgrespw
  jpa:
    hibernate.ddl-auto: create-drop
jwt:
  secret: eyJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJTb2NpYWxNZWRpYUFwaSIsIlVzZXJuYW1lIjoiVXNlciIsImV4cCI6MTY4NTcwMDc1OCwiaWF0IjoxNjg1NzAwNzU4fQ.0fbNbWfbpebV0dKnBWmknMldFvPZvSLxhi1eI2rvvHXFhnSQohtWW5bMjjatDVQ19gTHfYX3kvOX6vd947DYaA
  expiration: 86400000